# entradas
GET https://api.delbank.com.br/baas/api/v2/transactions
?limit=9999999
&isCredit=true
&startDate=01/01/2024
# &endDate=02/23/2024
# MES/DIA/ANO
x-delbank-api-key: Ic0q N8fw7g5Yang0QlcAQqknmOGungc2dJlvDsjQ6UjsDvurf8PLHyku2KpLmtLxAMgSM2StLQa+eSLh3ieiQHXb9PZLZ1YMevjwa1op+S0/tgOBdEi66vXINbPKtfIr

###

# saídas
GET https://api.delbank.com.br/baas/api/v2/transactions
?limit=9999999
&isCredit=false
&startDate=01/01/2024
# &endDate=02/23/2024
# MES/DIA/ANO
x-delbank-api-key: Ic0q N8fw7g5Yang0QlcAQqknmOGungc2dJlvDsjQ6UjsDvurf8PLHyku2KpLmtLxAMgSM2StLQa+eSLh3ieiQHXb9PZLZ1YMevjwa1op+S0/tgOBdEi66vXINbPKtfIr
